os:
- linux
sudo: false
language: python
python:
- "3.6"
install:
- pip install pipenv
- pipenv install --dev
script:
# TODO https://github.com/pypa/pipenv/issues/1050
#- pipenv check .

- pipenv check --style .
- pipenv run mypy aiocrypto_prices/ --ignore-missing-imports --strict-optional
- pipenv run python -m pytest tests --cov=aiocrypto_prices -v --durations=5
